import Head from 'next/head'; 
import { Header, Navigation, About } from '@/components/'

// import { mainData } from '@/lib/data' ;

export default function Home() {
  return (
    <>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        {/*header*/}
        <Header />
        {/* Main row */}
        <main>
          <div className="row g-4 g-lg-5">
             <div className="col-12 col-lg-4 col-xl-3">
              <Navigation />
            </div>
            <div className="col-12 col-lg-8 col-xl-9">
                 <div className="sections-wrapper">
                            {/* About Section */}
                            <About />
            </div>
          </div>
        </div>
        </main>
       

      </div>
    </>
  )
}
