import Head from 'next/head'; 
import { Header, Navigation } from '@/components/'

// import { mainData } from '@/lib/data' ;

export default function Home() {
  return (
    <>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        {/*header*/}
        <Header />

        <div>
                  <Navigation />

        </div>
        

        <div className="sections-wrapper">

        </div>

      </div>
    </>
  )
}
